apiVersion: v1
kind: Service
metadata:
  name: skaffold-spring-boot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: skaffold-spring-boot
    tier: frontend
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 8080
#    targetPort: http-server
#    name: frontend
#  - port: 8081
#    targetPort: 8081
#    name: management
#  selector:
#    app: skaffold-spring-boot
